# Les següents dues linies serien el fitxer .latexmkrc minim per a que tot funcioni simplement fent latexmk main.tex
# $pdf_mode = 5;  # xelatex
# $xelatex = 'xelatex -interaction=nonstopmode -shell-escape %O %S';
#

# ============================================================
# .latexmkrc — latexmk configuration file
# Place this file in the root of your project (next to main.tex)
# ============================================================


# ------------------------------------------------------------
# COMPILER
# ------------------------------------------------------------
# Tells latexmk which engine to use to produce the PDF.
# 1 = pdflatex, 4 = lualatex, 5 = xelatex
# The use of lualatex is intended for better math/physics typesetting: unicode-math support,
# proper Unicode math fonts (STIX2, Latin Modern Math, etc.), and it handles
# Catalan/accented characters identically to xelatex.
$pdf_mode = 4;

# The actual command latexmk runs when compiling.
# %O = options passed by latexmk internally (do not remove)
# %S = the source file, i.e. main.tex (do not remove)
#
# -interaction=nonstopmode  do not pause on errors, just log them
# -synctex=1                generate a .synctex.gz file, which lets
#                           editors like VS Code jump between a click
#                           in the PDF and the corresponding source line
# -shell-escape             required by the 'minted' package (code highlighting)
#                           to call Python's Pygments externally
#                           to call Python's Pygments externally
# -file-line-error          show errors as file:line: message instead of l.35,
#
$lualatex = 'lualatex -interaction=nonstopmode -synctex=1 -shell-escape -file-line-error %O %S';
# $pdflatex = 'pdflatex -interaction=nonstopmode -shell-escape -file-line-error %O %S';
# $xelatex  = 'xelatex  -interaction=nonstopmode -synctex=1 -shell-escape -file-line-error %O %S';


# ------------------------------------------------------------
# PDF VIEWER
# ------------------------------------------------------------
# The program latexmk uses to open the PDF.
# Combined with the -pvc flag, the PDF opens automatically on
# first compile and refreshes whenever you save a .tex file.
#
# 'start' is the Windows command to open a file with its default
# associated program — in this case your default PDF viewer.
$pdf_previewer = 'start'; # Windows opens default pdf viewer application
# $pdf_previewer = 'evince';       # Linux
# $pdf_previewer = 'open';         # macOS
# Combined with -pvc this means the PDF opens automatically on first compile and updates as you work.


# ------------------------------------------------------------
# OUTPUT DIRECTORY
# ------------------------------------------------------------
# Redirect all generated files (aux, log, bbl, pdf, etc.) into
# a subdirectory to keep the project root clean.
# The folder is created automatically if it does not exist.
$out_dir = 'build';
# This prevents xelatex from generating an empty Text_files directory 
# in the build folder

# This explicitly separates where the auxiliary files go
# from where the .pdf goes and stops latexmk from 
# mirroring the source tree in the build folder
# this prevents the above problem but for any added folders
# besides text_files
$aux_dir = 'build';

# ------------------------------------------------------------
# EXTRA EXTENSIONS TO CLEAN
# ------------------------------------------------------------
# When you run 'latexmk -c', latexmk deletes auxiliary files but
# keeps the PDF. By default it misses a few common extensions.
# This line appends our extras to the default list it already has.
#
# synctex.gz        the SyncTeX file generated by -synctex=1
# synctex(busy)     temporary SyncTeX lock file sometimes left behind
# xdv: intermediate file produced by xelatex
# run.xml: left behind by biber after each bibliography run
@generated_exts = (@generated_exts, 'synctex.gz', 'synctex(busy)', 'xdv', 'run.xml');
# This deletes ALL subdirectories in build/ before each compile run.
# Needed because \import mirrors the source tree (e.g. build/Text_files),
# and stale mirrored dirs cause latexmk to think files are missing.
$compiling_cmd = $^O eq 'MSWin32'
    ? 'cmd /c if /d %D in (build\*) do rmdir /s /q "%D"'
    : 'find build -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +';


